change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '' 

# PRにmajor or minor or patch のラベルを利用することで、自動生成されるtagのversionを変更できる
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION